language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn run test:unit
after_script:
  - cat ./coverage/lcov.info | coveralls
notifications:
  email:
    on_success: never
    on_failure: always
